# Generated by Django 4.2 on 2023-08-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cf_handle', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cc_handle', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ac_handle', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
