# Generated by Django 4.2 on 2023-08-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=1000)),
                ('score', models.PositiveIntegerField(default=100)),
                ('online_judge', models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'Codechef'), ('atcoder', 'Atcoder')], max_length=20)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest.contest')),
            ],
        ),
    ]
